import Head from "next/head";
import axios from "axios";

import Styles from "@/styles/Home.module.css";

import SearchBox from "../components/SearchBox/SearchBox";
import Cities from "../../utility/Cities/Cities";
import Activities from "../../utility/Activities/Activities";
import Venues from "../../utility/Venues/Venues";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Airbnb Clone</title>
        <meta
          name="description"
          content="A personal website generated by create next app for development practise"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={`row ${Styles.SearchBoxContainer}`}>
          <div className="col s9 m6 l6 xl3  offset-s1 offset-m1 offset-l1 offset-xl1">
            <SearchBox />
          </div>
        </div>
        <div className={Styles.LowerContainer}>
          <Cities
            cities={props.recommendedCities}
            header="Recommended cities for you"
          />
          <Activities
            activities={props.todayActivities}
            header="Today in your area"
          />
          <Cities cities={props.europeCities.cities} header={props.europeCities.header} />
          <Cities cities={props.asiaCities.cities} header={props.asiaCities.header} />
          <Venues
            venues={props.recommendedVenues.venues}
            header={props.recommendedVenues.header}
          />
          <Cities cities={props.exoticCities.cities} header={props.exoticCities.header} />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  // promises for data request
  const getDataPromises = [];
  // push the promises back from axios
  getDataPromises.push(
    axios.get(`${process.env.NEXT_PUBLIC_API_KEY}/cities/recommended`)
  );
  getDataPromises.push(
    axios.get(`${process.env.NEXT_PUBLIC_API_KEY}/cities/europe`)
  );
  getDataPromises.push(
    axios.get(`${process.env.NEXT_PUBLIC_API_KEY}/cities/asia`)
  );
  getDataPromises.push(
    axios.get(`${process.env.NEXT_PUBLIC_API_KEY}/cities/exotic`)
  );
  getDataPromises.push(
    axios.get(`${process.env.NEXT_PUBLIC_API_KEY}/activities/today`)
  );
  getDataPromises.push(
    axios.get(`${process.env.NEXT_PUBLIC_API_KEY}/venues/recommended`)
  );
  // resolve promises
  const responseData = await Promise.all(getDataPromises);
  return {
    props: {
      recommendedCities: responseData[0].data,
      europeCities: responseData[1].data,
      asiaCities: responseData[2].data,
      exoticCities: responseData[3].data,
      todayActivities: responseData[4].data,
      recommendedVenues: responseData[5].data,
    },
  };
}
